#!/bin/bash-*-Shell-script-modules*-

# This script is responsible for loading modules that are
# compatible with the NUOPC Layer version used in NEMS.

####################
### (1) Load all needed environment modules.
#module purge
#module load intel impi
#module load szip hdf5
#module load netcdf

#module load esmf


####################
### (2) Set some environments varaiables related to the loaded
###     modules and required to compile the NEMS application properly.

export HDF5HOME=
export NETCDFHOME=

export NETCDF_INCDIR=
export NETCDF_LIBDIR=

export ESMFMKFILE=
