#!/bin/bash-*-Shell-script-functions*-

###########################################################################
### Author:  Panagiotis Velissariou <panagiotis.velissariou@noaa.gov>
###
### Version - 1.1
###
###   1.1 Sun Mar 06 2022
###   1.0 Fri Dec 04 2020
###########################################################################

set +u

###====================
# Make sure that the current working directory is in the PATH
[[ ! :$PATH: == *:".":* ]] && export PATH="${PATH}:."

# Get the directory where the script is located
if [[ $(uname -s) == Darwin ]]; then
  src_name="$( grealpath -s "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}" )"
  src_dir="$(cd "$(dirname "${src_name}" )" && pwd -P)"
else
  src_name="$( realpath -s "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}" )"
  src_dir="$(cd "$(dirname "${src_name}" )" && pwd -P)"
fi

lst="${src_dir:+${src_dir}/}functions_utilities ${src_dir:+${src_dir}/}scripts/functions_utilities functions_utilities"
funcs=
for ilst in ${lst}
do
  if [ -f "${ilst:-}" ]; then
    funcs="${ilst}"
    break
  fi
done

if [ -n "${funcs:+1}" ]; then
  source "${funcs}"

  if [ $? -ne 0 ]; then
    echo " ### ERROR :: in ${src_name}"
    echo "     Cannot load the required file: ${funcs}"
    echo "     Exiting now ..."
    echo

    unset src_name src_dir ilst funcs
    return 1
  fi
else
  echo " ### ERROR :: in ${src_name}"
  echo "     Cannot load the required file: functions_utilities"
  echo "     Exiting now ..."
  echo

  unset src_name src_dir ilst funcs
  return 1
fi

unset src_name src_dir ilst funcs
###====================


export MY_COMPILING_SYTEMS="gnu, intel, pgi"
export MY_COMPILER_DEFAULT="intel"
export MY_COMPILING_PLATFORMS="custom, linux, macosx, cheyenne, gaea, hera, jet, orion, stampede, wcoss, mistral, strand"

########################################
##### Atmospheric components
MY_ATM_MODS="ATMESH PAHM"
#MY_ATM_MODS="ATMESH WRF HWRF PAHM"

##### Ocean components
MY_OCN_MODS="ADCIRC"
#MY_OCN_MODS="ADCIRC SCHISM FVCOM ROMS"

##### Hydrologic components
MY_HYD_MODS="NWM"

##### Wave components
MY_WAV_MODS="WW3DATA WW3"

##### Miscellaneous components
MY_MSC_MODS="BARDATA"
########################################

export MY_COMPONENT_DEFAULT="ADCIRC WW3DATA ATMESH"
export MY_COMPONENT_LIST="${MY_ATM_MODS} ${MY_OCN_MODS} ${MY_HYD_MODS} ${MY_WAV_MODS} ${MY_MSC_MODS}"


##################################################
### BEG:: MODELLING SYSTEM BUILD FUNCTIONS
##################################################

###========================================
### ParseArgs()
###
### Usage:      ParseArgs args
###
### Parameters: args = the script options
###
### Returns:    0
###
### Echoes:     NONE
###
### Gets the supplied options to the script.
###========================================
ParseArgs()
{
  local nm_func=$( basename ${BASH_SOURCE[${#BASH_SOURCE[@]}-1]} )

  local opt_all opt_opt opt_arg opt_chk

  local t_VAR
  local ans0 ans ival intN
  local all_evars

  all_evars="MY_ACCEPT_ALL MY_CLEAN MY_COMPILER MY_COMPONENT MY_EXECUTABLES MY_OS
             MY_PARALLEL MY_PARMAKE MY_PLATFORM MY_VERBOSE"

  for ival in ${all_evars}; do unset __${ival}; done


  __MY_ACCEPT_ALL=0
  __MY_CLEAN=0
  __MY_EXECUTABLES=
  __MY_COMPILER="${MY_COMPILER_DEFAULT}"
  __MY_COMPONENT="${MY_COMPONENT_DEFAULT}"
  __MY_OS=
  __MY_PARALLEL=1
  __MY_PARMAKE=1
  __MY_PLATFORM=
  __MY_VERBOSE=
          

  # -----
  # Process the function options
  opt_all=( accept_all build_exec c clean compiler component j par parallel os plat platform v verbose h help )
  opt_all=":$( echo "${opt_all[@]/#/-} ${opt_all[@]/#/--}" | sed 's/ /:/g' ):"

  unset __OPTION_LIST
  while test $# -gt 0; do
    case "${1}" in
      -[^-]*=* | --[^-]*=* )
        opt_opt="$( toLOWER "$( echo "${1}" | sed 's/=.*//' )" )"
        len=$(( ${#opt_opt} + 1 ))
        opt_arg="$( strTrim "$( echo "${1:${len}}" )" 2 )"
        [ "$( echo "${opt_all}" | egrep -o ":${opt_arg}:" )" ] && \
          opt_arg=
        ;;
      -[^-]* | --[^-]* )
        opt_opt="$( toLOWER "${1}" )"
        opt_chk="$( toLOWER "$( echo "${2}" | sed 's/=.*//' )" )"
        if [ "$( echo "${opt_all}" | egrep -o ":${opt_chk}:" )" ]; then
          opt_arg=
        else
          opt_arg="$( strTrim "$( echo "${2}" )" )"
        fi
        ;;
      *)
        opt_opt=
        opt_arg=
        ;;
    esac

    case "${opt_opt}" in
      -build_exec | --build_exec )
          checkFuncOpt "--build_exec"
          if [ $? -eq 0 ]; then
            if [ "X${opt_arg}" != "X" ]; then
              __MY_EXECUTABLES="$( strTrim "${opt_arg}" )"
            fi
          fi
        ;;
      -c | --c | -clean | --clean )
          checkFuncOpt "--clean"
          if [ $? -eq 0 ]; then
            __MY_CLEAN=1
            if [ "X${opt_arg}" != "X" ]; then
              if `isInteger "${opt_arg}"` ; then
                __MY_CLEAN=$( echo "${opt_arg}" )
                [ ${opt_arg} -le -3 ] && __MY_CLEAN=-3
                [ ${opt_arg} -ge  2 ] && __MY_CLEAN=2
              else
                __MY_CLEAN=0
                [ "$( getYesNo "${opt_arg}" )" = "yes" ] && __MY_CLEAN=1
              fi
            fi
          fi
        ;;
      -compiler | --compiler )
          checkFuncOpt "--compiler"
          if [ $? -eq 0 ]; then
            if [ "X${opt_arg}" != "X" ]; then
              __MY_COMPILER="$( echo "${opt_arg}" | sed 's/[[:space:]]//g' )"
            fi
          fi
        ;;
      -component | --component )
          checkFuncOpt "--component"
          if [ $? -eq 0 ]; then
            if [ "X${opt_arg}" != "X" ]; then
              __MY_COMPONENT="$( strTrim "${opt_arg}" )"
            fi
          fi
        ;;
      -j | --j )
          checkFuncOpt "--j"
          if [ $? -eq 0 ]; then
            if [ "X${opt_arg}" != "X" ]; then
              __MY_PARMAKE=1
              t_VAR="$( getPosInteger "${opt_arg}" )"
              [ ! -z "${t_VAR}" ] && __MY_PARMAKE=${t_VAR}
            fi
          fi
        ;;
      -par | --par | -parallel | --parallel )
          checkFuncOpt "--parallel"
          if [ $? -eq 0 ]; then
            __MY_PARALLEL=1
            if [ "X${opt_arg}" != "X" ]; then
              if `isInteger "${opt_arg}"` ; then
                __MY_PARALLEL=0
                [ ${opt_arg} -ge 1 ] && __MY_PARALLEL=1
              else
                __MY_PARALLEL=0
                [ "$( getYesNo "${opt_arg}" )" = "yes" ] && __MY_PARALLEL=1
              fi
            fi
          fi
        ;;
      -os | --os )
          checkFuncOpt "--os"
          if [ $? -eq 0 ]; then
            if [ "X${opt_arg}" != "X" ]; then
              __MY_OS="$( echo "${opt_arg}" | sed 's/[[:space:]]//g' )"
            fi
          fi
        ;;
      -plat | --plat | -platform | --platform)
          checkFuncOpt "--platform"
          if [ $? -eq 0 ]; then
            if [ "X${opt_arg}" != "X" ]; then
              __MY_PLATFORM="$( echo "${opt_arg}" | sed 's/[[:space:]]//g' )"
            fi
          fi
        ;;
      -v | --v | -verbose | --verbose )
          checkFuncOpt "--verbose"
          if [ $? -eq 0 ]; then
            __MY_VERBOSE=b # This is suitable for GNU's make
            if [ "X${opt_arg}" != "X" ]; then
              __MY_VERBOSE="${opt_arg}"
            fi
            __MY_VERBOSE="$( getMakeVerbosity "${__MY_VERBOSE}" )"
          fi
        ;;
      -y | --y | -yes | --yes )
          checkFuncOpt "--yes"
          if [ $? -eq 0 ]; then
            __MY_ACCEPT_ALL=1
            if [ "X${opt_arg}" != "X" ]; then
              if `isInteger "${opt_arg}"` ; then
                __MY_ACCEPT_ALL=$( echo "${opt_arg}" )
                [ ${opt_arg} -le 0 ] && __MY_ACCEPT_ALL=0
                [ ${opt_arg} -ge 1 ] && __MY_ACCEPT_ALL=1
              else
                __MY_ACCEPT_ALL=0
                [ "$( getYesNo "${opt_arg}" )" = "yes" ] && __MY_ACCEPT_ALL=1
              fi
            fi
          fi
        ;;
      -h | -help | --h | --help )
          UsageBuild ${nm_func}
        ;;
      *) ;; # DEFAULT
    esac
    shift
    opt_opt= 
    opt_arg=
  done
  unset __OPTION_LIST
  # -----

  if [ -z "${__MY_OS}" ]; then
    case "$(uname -s)" in
      Darwin ) __MY_OS="macosx" ;;
      Linux  ) __MY_OS="linux"  ;;
            *) __MY_OS="linux"  ;; # DEFAULT
    esac
  fi

  if [ -z "${__MY_PLATFORM}" ]; then
    case "$(uname -s)" in
      Darwin ) __MY_PLATFORM="macosx" ;;
      Linux  ) __MY_PLATFORM="linux"  ;;
            *) __MY_PLATFORM="linux"  ;; # DEFAULT
    esac
  fi

  # Export the values of all __* variables.
  for ival in ${all_evars}
  do
    ans0="$( eval "echo \${$(echo ${ival}):-}" )"
    ans="$( eval "echo \${$(echo __${ival}):-}" )"
    ans=${ans:-${ans0:-}}

    eval "${ival}=\${ans}"
    export ${ival}

    unset __${ival}
  done

  return 0
}

###========================================
### UsageBuild()
###
### Usage:      UsageBuild
###
### Parameters: NONE
###
### Returns : Exits on error
###
### Exports : NONE
###
### Echoes  : NONE
###
### UsageBuild: Prints all usage options of the build script.
###========================================
UsageBuild()
{
  local nm="$( basename ${0} )"

  echo
  echo "Usage: \"${nm}\" [{-|--}option1{=|space}[option_value1]] [{-|--}option2{=|space}[option_value2]] ..."
  echo

  echo "  -h|-help|--h|--help"
  echo "    Show this help screen."
  echo
  #---
  echo "  -y|-yes|--y|--yes"
  echo "    Automatically answer yes for all questions."
  echo "    Default: 0|no (user is required to enter a yes/no response)."
  echo
  #---
  echo "  -c|--c|-clean|--clean [=|space] \"0|1|yes|no\" (OPTIONAL)."
  echo "    Only clean the already compiled CMake build system."
  echo "    Default: 0|no."
  echo
  #---
  echo "  -compiler|--compiler [=|space] \"compiling_system\" (OPTIONAL)."
  echo "    The compiling system to use (${MY_COMPILING_SYTEMS})."
  echo "    Default: ${MY_COMPILER_DEFAULT}."
  echo
  #---
  echo "  -component|--component [=|space] \"component_list\" (OPTIONAL)."
  echo "    The component(s) to use (${MY_COMPONENT_LIST})."
  echo "    Default: \"${MY_COMPONENT_DEFAULT}\"."
  echo
  #---
  echo "  -build_exec|--build_exec [=|space] \"executable_list\" (OPTIONAL)."
  echo "    The executables(s) to build (e.g. --build_exec=\"padcirc pahm\")."
  echo "    Default: none."
  echo
  #---
  echo "  -j|--j [=|space] \"N\" (OPTIONAL)."
  echo "    Define the number of make jobs to run simultaneously."
  echo "    Default: 1."
  echo
  #---
  echo "  -par|--par|-parallel|--parallel [=|space] \"0|1|yes|no\" (OPTIONAL)."
  echo "    Activate the use of parallel compilers."
  echo "    Default: 1|yes."
  echo
  #---
  echo "  -os|--os [=|space] \"OS string\" (OPTIONAL)."
  echo "    The name of the Operating system."
  echo "    Supported OSes: linux macosx."
  echo "    Default: current OS."
  echo
  #---
  echo "  -plat|--plat|-platform|--platform [=|space] \"platform\" (OPTIONAL)."
  echo "    The name of the compute HPC platform to consider."
  echo "    Selecting a platform, environment modules specific to that platform are loaded"
  echo "    and corresponding environment variables are set."
  echo "    Supported platforms: ${MY_COMPILING_PLATFORMS}."
  echo "    Default: OS."
  echo
  #---
  echo "  -v|--v|-verbose|--verbose [=|space] \"a,b,v,i,j,m,n\" (any combination, OPTIONAL)."
  echo "    Enable verbosity in the make files during compilation."
  echo "      a (all)      : all types of debugging output are enabled"
  echo "      n (none)     : disable all debugging currently enabled"
  echo "      b (basic)    : basic debugging and whether the build was successful or not"
  echo "      v (verbose)  : a level above basic"
  echo "      i (implicit) : prints messages describing the implicit rule searches for each target"
  echo "      j (jobs)     : prints messages giving details on the invocation of specific sub-commands"
  echo "      m (makefile) : enables messages while rebuilding makefiles"
  echo "    Default:none."
  echo
  #---

  exit 0
}

###========================================
### getNEMSEnvVars()
###
### Usage:      getNEMSEnvVars
###
### Parameters: NONE
###
### Returns : error status
###
### Exports : CLEAN COMPILER COMPONENT PARALLEL BUILD_EXECS OS PLATFORM PARMAKE VERBOSE
###           NEMS_COMPILER NEMS_PARALLEL NEMS_PLATFORM MACHINE_ID FULL_MACHINE_ID
###           APP_DIR APPMODS_DIR modFILE modDIR NEMS_DIR compFNAME
###
### Echoes  : NONE
###
### getNEMSEnvVars: Exports all the NEMS environment variables.
###========================================
 getNEMSEnvVars() {
  local src_name src_dir component_ww3


  if [ -n "${APP_DIR:+1}" ]; then
    src_dir="${APP_DIR}"
  else
    if [ -n "${1:+1}" ]; then
      src_dir="${1}"
    else
      # Get the directory where the script is located
      if [[ $(uname -s) == Darwin ]]; then
        readonly src_name="$( grealpath -s "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}" )"
        readonly src_dir="$(cd "$(dirname "${src_name}" )" && pwd -P)"
      else
        readonly src_name="$( realpath -s "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}" )"
        readonly src_dir="$(cd "$(dirname "$(realpath -s "${BASH_SOURCE[0]}")" )" && pwd -P)"
      fi
    fi
  fi
  APP_DIR=${src_dir}
 
  ACCEPT_ALL=${MY_ACCEPT_ALL}
  export ACCEPT_ALL=${ACCEPT_ALL:-0}

  CLEAN=${MY_CLEAN}
  export CLEAN=${CLEAN:-0}

  COMPILER="$( toLOWER "$( basename "${MY_COMPILER}" )" )"
  export COMPILER=${COMPILER:-}

  COMPONENT="$( toUPPER "${MY_COMPONENT}" )"
  export COMPONENT=${COMPONENT:-}

  PARALLEL=${MY_PARALLEL}
  export PARALLEL=${PARALLEL:-1}

  BUILD_EXECS="${MY_EXECUTABLES}"
  export BUILD_EXECS=${BUILD_EXECS:-}

  OS="$( toLOWER "${MY_OS}" )"
  export OS=${OS:-}

  if [ -n "${MY_PLATFORM:+1}" ]; then
    PLATFORM="$( toLOWER "${MY_PLATFORM}" )"
  else
    PLATFORM="${OS}"
  fi
  export PLATFORM=${PLATFORM:-}

  PARMAKE=${MY_PARMAKE}
  export PARMAKE=${PARMAKE:-1}

  VERBOSE="${MY_VERBOSE}"
  export VERBOSE=${VERBOSE:-}

  ##### Customize the NEMS.x filename to include the component names
  compFNAME=
  if [ -n "${COMPONENT:+1}" ]; then
    compFNAME="$( strTrim "$( toLOWER "${COMPONENT}" )" )"
    compFNAME="$( echo "${compFNAME}" | sed 's/ /_/g' )"
  fi
  export compFNAME=${compFNAME:-}
  #####

  ##### Get the WW3 related environment variables
  WW3_CONFOPT=
  WW3_COMP=
  WWATCH3_NETCDF=
  component_ww3="$( echo "${COMPONENT}" | sed 's/ /:/g' )"
  if [[ :${component_ww3}: == *:"WW3":* ]]; then
    WW3_CONFOPT="${COMPILER}"
    WW3_COMP="${COMPILER}"
    WWATCH3_NETCDF=NC4
  fi
  export WW3_CONFOPT=${WW3_CONFOPT:-}
  export WW3_COMP=${WW3_COMP:-}
  export WWATCH3_NETCDF=${WWATCH3_NETCDF:-}
  #####
  
  # Export some important environment variables for NEMS and for other models
  export NEMS_COMPILER="${COMPILER:-}"
  export NEMS_PARALLEL="${PARALLEL:-}"
  export NEMS_PLATFORM="${PLATFORM:-}"
  export MACHINE_ID="${PLATFORM:-}"
  export FULL_MACHINE_ID="${PLATFORM:-}"

  export APP_DIR="${APP_DIR:-}"
  export APPMODS_DIR="${APPMODS_DIR:-${APP_DIR:+${APP_DIR}/}modulefiles}"

  # This used in NEMS to get the configuration flags for the chosen compiler
  # in the top level conf directory. Supported OSes are linux and macosx.
  # Sometimes we might need to specify special flags not founf in the default
  # files for s pecific platform
  if [ ! -f "${APP_DIR}/conf/configure.nems.${FULL_MACHINE_ID}.${NEMS_COMPILER}" ]; then
    export BUILD_TARGET=${OS}.${NEMS_COMPILER}
  else
    export BUILD_TARGET="${FULL_MACHINE_ID}.${NEMS_COMPILER}"
  fi

  if [ ! -f "${APP_DIR}/conf/externals.nems.${FULL_MACHINE_ID}" ]; then
    export EXTERNALS_NEMS="externals.nems"
  else
    export EXTERNALS_NEMS="externals.nems.${FULL_MACHINE_ID}"
  fi

  # Get the project directories and perform a basic check on them
  readonly NEMS_DIR="${APP_DIR}/NEMS"
  if [ ! -f "${NEMS_DIR}/NEMSAppBuilder" ]; then
    echo "The project directory \"${NEMS_DIR}\" does not appear to contain NEMSAppBuilder."
    echo "Is this the correct NEMS directory?"
    echo "You might need to set the environment variable APP_DIR before running this script."
    echo "Exiting ..."
    exit 1
  fi
  export NEMS_DIR

  # ADCIRC specific (this might change in the future)
  if [ -d "${APP_DIR}/ADCIRC/thirdparty/datetime-fortran" ]; then
    export DATETIMEHOME=${APP_DIR}/ADCIRC/thirdparty/datetime-fortran
  fi

  modFILE="envmodules${COMPILER:+_${COMPILER}}${PLATFORM:+.${PLATFORM}}"
  if [ ! -f "${APPMODS_DIR}/${modFILE}" ]; then
    echo
    echo "The modulefiles directory \"${modDIR}\" does not appear to contain the module file: ${modFILE}."
    echo "Is this the correct \"modulefiles\" directory?"
    echo "You might need to set the environment variable \"APPMODS_DIR\" to point to a custom modulefiles directory before running this script."
    echo "Exiting ..."
    echo
    exit 1
  else
    # Source the environment module
    export modFILE="${APPMODS_DIR}/${modFILE}"
    source ${modFILE} 2>/dev/null
  fi
}

###========================================
### checkNEMSComponents()
###
### Usage:      checkNEMSComponents
###
### Parameters: NONE
###
### Returns : Exits on error
###
### Exports : NONE
###
### Echoes  : NONE
###
### checkNEMSComponents: Checks if a user supplied modeling component is supported.
###========================================
 checkNEMSComponents() {
  local comp_user comp_all
  local icomp

  comp_user="$( toUPPER "${COMPONENT}" )"
  [ -z "${comp_user}" ] && \
    comp_user="$( toUPPER "${MY_COMPONENT}" )"

  comp_all="$( toUPPER "${MY_COMPONENT_LIST}" )"

  for icomp in ${comp_user}
  do
    if [[ "${comp_all}" != *"${icomp}"* ]]; then
      echo "The modeling component \"${icomp}\" is not supported."
      echo "Please adjust your component list and re-run the script."
      echo "Exiting ..."
      exit 1
      echo "icomp = ${icomp}"
    fi
  done
}

###========================================
### compileNems()
###
### Usage:      compileNems compile_type
###
### Parameters: compile_type = one of: clean|distclean or, build|compile
###
### Returns : error status
###
### Exports : NONE
###
### Echoes  : NONE
###
### compileNems: Uses environment variables to compile a NEMS application.
###========================================
compileNems() {
  local cmp_type cmp_make cmp_comp cmp_mjob
  local err=0

  [ $# -eq 0 ] && return ${err}

  cmp_type="$( toLOWER "${1}" )"
  cmp_make=GNUmakefile   # This is the top level NEMS Makefile
  cmp_comp="${COMPONENT:+COMPONENTS=\"${COMPONENT}\"}"
  cmp_mjob="${PARMAKE:+-j ${PARMAKE}}"
  cmp_verb="${VERBOSE:+--debug=${VERBOSE}}"

  case "${cmp_type}" in
    "clean"|"distclean" )
      if [ -f  "${cmp_make}" ]; then
        echo
        echo "compileNems :: Cleaning: make -f ${cmp_make} ${cmp_type} ${cmp_comp}"
        eval "make ${cmp_verb} -f ${cmp_make} ${cmp_type} ${cmp_comp}"
        err=$?
        if [ "${cmp_type}" = "distclean" ]; then
          rm -fv exe/NEMS*.x
        fi
      else
        echo "compileNems :: Cleaning: no makefile found: makefile = ${cmp_make}"
        err=1
      fi
      ;;
    "build"|"compile" )
      if [ -f  "${cmp_make}" ]; then
        echo
        echo "compileNems :: Compiling: make ${cmp_mjob} -f ${cmp_make} ${cmp_type} ${cmp_comp}"
        eval "make ${cmp_verb} ${cmp_mjob} -f ${cmp_make} ${cmp_type} ${cmp_comp}"
        err=$?
      else
        echo "compileNems :: Compiling: no makefile found: makefile = ${cmp_make}"
        err=1
      fi
      ;;
    * ) err=0 ;; # Do nothing
  esac

  return ${err}
}

###========================================
### installNems()
###
### Usage:      installNems compile_type
###
### Parameters: NONE
###
### Returns : NONE
###
### Exports : NONE
###
### Echoes  : NONE
###
### installNems: Installs all NEMS compiled components.
###========================================
# Need to have specific model components install functions
# TODO - Panagiotis Velissariou
installNems() {
  local cmp_comp icmp
  local instdir
  local CPBIN="/bin/cp -fpv"
  local RMBIN="/bin/rm -fv"

  instdir="ALLBIN_INSTALL"

  cmp_comp="${COMPONENT}"

  [ ! -d "${instdir}" ] && mkdir -p ${instdir}

  for icmp in ${cmp_comp}
  do
    indir="${icmp}_INSTALL"
    
    if [ -d ${indir} ]; then
      echo
      echo "   --- Installing from: ${indir} to ${instdir} ---"
      ${CPBIN} ${indir}/* ${instdir}/
    fi

    ###### Extra ADCIRC files
    if [ "${icmp}" == "ADCIRC" ]; then
      echo
      echo "   --- Installing from: ${icmp} to ${instdir} ---"
      for iprog in adcprep aswip adcirc padcirc tide_fac
      do
        prog="$( find -L ${icmp} -type f -name ${iprog} | head -1 )"

        if [ -n "${prog:+1}" ]; then
          ${CPBIN} ${prog} ${instdir}/
        fi
      done
    fi
    ######
  done

  ###### Install the NEMS/exe/NEMS* files
  echo
  echo "   --- Installing from: NEMS/exe to ${instdir} ---"
  for iprog in NEMS/exe/NEMS*.x
  do
    if [ -f "${iprog}" ]; then
      ${CPBIN} ${iprog} ${instdir}/
    fi
  done

  ###### Remove un-needed files from instdir
  echo
  echo "   --- Removing files that are not needed from: ${instdir} ---"
  ${RMBIN} ${instdir}/*.mk ${instdir}/*.mod
}
